[package]
name = "dummy-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mazeio-shared = {path = "../shared"}
clap = {version = "3.0", features=["derive"]}